package com.rule

import com.javainuse.model.Product

rule "Offer for Iron"
	when
		productObject: Product(type=="iron")
	then
		productObject.setDiscount(10);
	end
rule "Offer for Diamond"
	when 
		productObject: Product(type=="diamond")
	then
		productObject.setDiscount(15);
	end
rule "Offer for Gold"
	when 
		productObject: Product(type=="gold")
	then
		productObject.setDiscount(25);
	end